/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./station.glb --keepnames --keepgroups --meta 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/station.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="coinoperatedbinocular" position={[-3.156, 1.681, -1.443]} rotation={[Math.PI, 0, Math.PI]} scale={0.009} userData={{ name: 'coinoperatedbinocular' }}>
          <mesh name="bolt_low" geometry={nodes.bolt_low.geometry} material={nodes.bolt_low.material} position={[69.727, 45.7, -28.641]} rotation={[3.085, -1.286, -0.054]} userData={{ name: 'bolt_low' }} />
        </group>
        <mesh name="Wireframe" geometry={nodes.Wireframe.geometry} material={nodes.Wireframe.material} userData={{ name: 'Wireframe' }} />
        <mesh name="Vert003" geometry={nodes.Vert003.geometry} material={nodes.Vert003.material} userData={{ name: 'Vert.003' }} />
        <mesh name="Vert004" geometry={nodes.Vert004.geometry} material={nodes.Vert004.material} userData={{ name: 'Vert.004' }} />
        <mesh name="Vert005" geometry={nodes.Vert005.geometry} material={nodes.Vert005.material} userData={{ name: 'Vert.005' }} />
        <mesh name="Sci-fi_Barrel_-_Standart" geometry={nodes['Sci-fi_Barrel_-_Standart'].geometry} material={nodes['Sci-fi_Barrel_-_Standart'].material} position={[-1.163, 0.102, 3.551]} scale={0.49} userData={{ name: 'Sci-fi Barrel - Standart' }} />
        <mesh name="Mailbox" geometry={nodes.Mailbox.geometry} material={nodes.Mailbox.material} position={[1.59, 0.468, -2.721]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.446} userData={{ name: 'Mailbox' }} />
        <mesh name="Wireframe001" geometry={nodes.Wireframe001.geometry} material={nodes.Wireframe001.material} userData={{ name: 'Wireframe.001' }} />
        <mesh name="Tank015" geometry={nodes.Tank015.geometry} material={nodes.Tank015.material} userData={{ name: 'Tank.015' }} />
        <mesh name="Pill003" geometry={nodes.Pill003.geometry} material={nodes.Pill003.material} userData={{ name: 'Pill.003' }} />
        <mesh name="Hatch007" geometry={nodes.Hatch007.geometry} material={nodes.Hatch007.material} userData={{ name: 'Hatch.007' }} />
        <mesh name="Tank014" geometry={nodes.Tank014.geometry} material={nodes.Tank014.material} userData={{ name: 'Tank.014' }} />
        <mesh name="Tank010" geometry={nodes.Tank010.geometry} material={nodes.Tank010.material} userData={{ name: 'Tank.010' }} />
        <mesh name="Tank013" geometry={nodes.Tank013.geometry} material={nodes.Tank013.material} userData={{ name: 'Tank.013' }} />
        <mesh name="Tank011" geometry={nodes.Tank011.geometry} material={nodes.Tank011.material} userData={{ name: 'Tank.011' }} />
        <mesh name="Tank012" geometry={nodes.Tank012.geometry} material={nodes.Tank012.material} userData={{ name: 'Tank.012' }} />
        <mesh name="Tank009" geometry={nodes.Tank009.geometry} material={nodes.Tank009.material} userData={{ name: 'Tank.009' }} />
        <mesh name="Pill002" geometry={nodes.Pill002.geometry} material={nodes.Pill002.material} userData={{ name: 'Pill.002' }} />
        <mesh name="Tank008" geometry={nodes.Tank008.geometry} material={nodes.Tank008.material} userData={{ name: 'Tank.008' }} />
        <mesh name="Hatch006" geometry={nodes.Hatch006.geometry} material={nodes.Hatch006.material} userData={{ name: 'Hatch.006' }} />
        <mesh name="Hatch005" geometry={nodes.Hatch005.geometry} material={nodes.Hatch005.material} userData={{ name: 'Hatch.005' }} />
        <mesh name="Hatch004" geometry={nodes.Hatch004.geometry} material={nodes.Hatch004.material} userData={{ name: 'Hatch.004' }} />
        <mesh name="Wireframe002" geometry={nodes.Wireframe002.geometry} material={nodes.Wireframe002.material} userData={{ name: 'Wireframe.002' }} />
        <mesh name="Tank002" geometry={nodes.Tank002.geometry} material={nodes.Tank002.material} userData={{ name: 'Tank.002' }} />
        <mesh name="Wireframe004" geometry={nodes.Wireframe004.geometry} material={nodes.Wireframe004.material} userData={{ name: 'Wireframe.004' }} />
        <mesh name="Pill" geometry={nodes.Pill.geometry} material={nodes.Pill.material} userData={{ name: 'Pill' }} />
        <mesh name="Hatch001" geometry={nodes.Hatch001.geometry} material={nodes.Hatch001.material} userData={{ name: 'Hatch.001' }} />
        <mesh name="Tank003" geometry={nodes.Tank003.geometry} material={nodes.Tank003.material} userData={{ name: 'Tank.003' }} />
        <mesh name="Tank006" geometry={nodes.Tank006.geometry} material={nodes.Tank006.material} userData={{ name: 'Tank.006' }} />
        <mesh name="Tank004" geometry={nodes.Tank004.geometry} material={nodes.Tank004.material} userData={{ name: 'Tank.004' }} />
        <mesh name="Tank001" geometry={nodes.Tank001.geometry} material={nodes.Tank001.material} userData={{ name: 'Tank.001' }} />
        <mesh name="Tank" geometry={nodes.Tank.geometry} material={nodes.Tank.material} userData={{ name: 'Tank' }} />
        <mesh name="Tank005" geometry={nodes.Tank005.geometry} material={nodes.Tank005.material} userData={{ name: 'Tank.005' }} />
        <mesh name="Pill001" geometry={nodes.Pill001.geometry} material={nodes.Pill001.material} userData={{ name: 'Pill.001' }} />
        <mesh name="Tank007" geometry={nodes.Tank007.geometry} material={nodes.Tank007.material} userData={{ name: 'Tank.007' }} />
        <mesh name="Hatch002" geometry={nodes.Hatch002.geometry} material={nodes.Hatch002.material} userData={{ name: 'Hatch.002' }} />
        <mesh name="Hatch003" geometry={nodes.Hatch003.geometry} material={nodes.Hatch003.material} userData={{ name: 'Hatch.003' }} />
        <mesh name="Hatch" geometry={nodes.Hatch.geometry} material={nodes.Hatch.material} userData={{ name: 'Hatch' }} />
        <mesh name="Wireframe005" geometry={nodes.Wireframe005.geometry} material={nodes.Wireframe005.material} userData={{ name: 'Wireframe.005' }} />
        <mesh name="Streetpole" geometry={nodes.Streetpole.geometry} material={nodes.Streetpole.material} userData={{ name: 'Streetpole' }} />
        <mesh name="Cable001" geometry={nodes.Cable001.geometry} material={nodes.Cable001.material} userData={{ name: 'Cable.001' }} />
        <mesh name="Cable" geometry={nodes.Cable.geometry} material={nodes.Cable.material} userData={{ name: 'Cable' }} />
        <mesh name="StreetpoleLight" geometry={nodes.StreetpoleLight.geometry} material={nodes.StreetpoleLight.material} userData={{ name: 'StreetpoleLight' }} />
        <mesh name="Hatch008" geometry={nodes.Hatch008.geometry} material={nodes.Hatch008.material} userData={{ name: 'Hatch.008' }} />
        <mesh name="Pill004" geometry={nodes.Pill004.geometry} material={nodes.Pill004.material} userData={{ name: 'Pill.004' }} />
        <mesh name="Pill005" geometry={nodes.Pill005.geometry} material={nodes.Pill005.material} userData={{ name: 'Pill.005' }} />
        <mesh name="Tank016" geometry={nodes.Tank016.geometry} material={nodes.Tank016.material} userData={{ name: 'Tank.016' }} />
        <mesh name="Hatch009" geometry={nodes.Hatch009.geometry} material={nodes.Hatch009.material} userData={{ name: 'Hatch.009' }} />
        <mesh name="Hatch010" geometry={nodes.Hatch010.geometry} material={nodes.Hatch010.material} userData={{ name: 'Hatch.010' }} />
        <mesh name="Tank017" geometry={nodes.Tank017.geometry} material={nodes.Tank017.material} userData={{ name: 'Tank.017' }} />
        <mesh name="ArrowPost" geometry={nodes.ArrowPost.geometry} material={nodes.ArrowPost.material} userData={{ name: 'ArrowPost' }}>
          <mesh name="ArrowSign" geometry={nodes.ArrowSign.geometry} material={nodes.ArrowSign.material} userData={{ name: 'ArrowSign' }} />
          <mesh name="LightArrow" geometry={nodes.LightArrow.geometry} material={nodes.LightArrow.material} userData={{ name: 'LightArrow' }} />
          <mesh name="LightArrows" geometry={nodes.LightArrows.geometry} material={nodes.LightArrows.material} userData={{ name: 'LightArrows' }} />
        </mesh>
        <mesh name="Barrel" geometry={nodes.Barrel.geometry} material={nodes.Barrel.material} userData={{ name: 'Barrel' }} />
        <mesh name="Barrel001" geometry={nodes.Barrel001.geometry} material={nodes.Barrel001.material} userData={{ name: 'Barrel.001' }} />
        <mesh name="WallBig" geometry={nodes.WallBig.geometry} material={nodes.WallBig.material} userData={{ name: 'WallBig' }} />
        <mesh name="BaseBigTop" geometry={nodes.BaseBigTop.geometry} material={nodes.BaseBigTop.material} userData={{ name: 'BaseBigTop' }} />
        <mesh name="RimWallBig" geometry={nodes.RimWallBig.geometry} material={nodes.RimWallBig.material} userData={{ name: 'RimWallBig' }} />
        <mesh name="StoreFrame" geometry={nodes.StoreFrame.geometry} material={nodes.StoreFrame.material} userData={{ name: 'StoreFrame' }} />
        <mesh name="BuildingTop" geometry={nodes.BuildingTop.geometry} material={nodes.BuildingTop.material} userData={{ name: 'BuildingTop' }}>
          <mesh name="Window001" geometry={nodes.Window001.geometry} material={nodes.Window001.material} userData={{ name: 'Window.001' }} />
        </mesh>
        <mesh name="Fan" geometry={nodes.Fan.geometry} material={nodes.Fan.material} position={[1.204, 0.78, -1.005]} userData={{ name: 'Fan' }} />
        <mesh name="Island" geometry={nodes.Island.geometry} material={nodes.Island.material} userData={{ name: 'Island' }} />
        <mesh name="LightBuildingMiddle" geometry={nodes.LightBuildingMiddle.geometry} material={nodes.LightBuildingMiddle.material} userData={{ name: 'LightBuildingMiddle' }} />
        <mesh name="LightBuildingTop" geometry={nodes.LightBuildingTop.geometry} material={nodes.LightBuildingTop.material} userData={{ name: 'LightBuildingTop' }} />
        <mesh name="LightSign" geometry={nodes.LightSign.geometry} material={nodes.LightSign.material} userData={{ name: 'LightSign' }} />
        <mesh name="Panels" geometry={nodes.Panels.geometry} material={nodes.Panels.material} userData={{ name: 'Panels' }} />
        <mesh name="Pilar1" geometry={nodes.Pilar1.geometry} material={nodes.Pilar1.material} userData={{ name: 'Pilar1' }} />
        <mesh name="Pilar2" geometry={nodes.Pilar2.geometry} material={nodes.Pilar2.material} userData={{ name: 'Pilar2' }} />
        <mesh name="Pipe" geometry={nodes.Pipe.geometry} material={nodes.Pipe.material} userData={{ name: 'Pipe' }} />
        <mesh name="Pipe001" geometry={nodes.Pipe001.geometry} material={nodes.Pipe001.material} userData={{ name: 'Pipe.001' }} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} userData={{ name: 'Plane' }} />
        <mesh name="Platforms" geometry={nodes.Platforms.geometry} material={nodes.Platforms.material} userData={{ name: 'Platforms' }} />
        <mesh name="Pump_roof" geometry={nodes.Pump_roof.geometry} material={nodes.Pump_roof.material} userData={{ name: 'Pump_roof' }} />
        <mesh name="Railings" geometry={nodes.Railings.geometry} material={nodes.Railings.material} userData={{ name: 'Railings' }} />
        <mesh name="Sign" geometry={nodes.Sign.geometry} material={nodes.Sign.material} userData={{ name: 'Sign' }} />
        <mesh name="Stairs" geometry={nodes.Stairs.geometry} material={nodes.Stairs.material} userData={{ name: 'Stairs' }} />
        <mesh name="Stairs001" geometry={nodes.Stairs001.geometry} material={nodes.Stairs001.material} userData={{ name: 'Stairs.001' }} />
        <mesh name="StreetlampLightGreen" geometry={nodes.StreetlampLightGreen.geometry} material={nodes.StreetlampLightGreen.material} userData={{ name: 'StreetlampLightGreen' }} />
        <mesh name="StreetlampLightOrange" geometry={nodes.StreetlampLightOrange.geometry} material={nodes.StreetlampLightOrange.material} userData={{ name: 'StreetlampLightOrange' }} />
        <mesh name="StreetlampLightRed" geometry={nodes.StreetlampLightRed.geometry} material={nodes.StreetlampLightRed.material} userData={{ name: 'StreetlampLightRed' }} />
        <mesh name="Text_77" geometry={nodes.Text_77.geometry} material={nodes.Text_77.material} userData={{ name: 'Text_77' }} />
        <mesh name="Text_Cloud" geometry={nodes.Text_Cloud.geometry} material={nodes.Text_Cloud.material} userData={{ name: 'Text_Cloud' }} />
        <mesh name="Text_Motel" geometry={nodes.Text_Motel.geometry} material={nodes.Text_Motel.material} userData={{ name: 'Text_Motel' }} />
        <mesh name="Text_Paradise" geometry={nodes.Text_Paradise.geometry} material={nodes.Text_Paradise.material} userData={{ name: 'Text_Paradise' }} />
        <mesh name="Text_Pitstop" geometry={nodes.Text_Pitstop.geometry} material={nodes.Text_Pitstop.material} userData={{ name: 'Text_Pitstop' }} />
        <mesh name="Tires" geometry={nodes.Tires.geometry} material={nodes.Tires.material} userData={{ name: 'Tires' }} />
        <mesh name="Vending-machine" geometry={nodes['Vending-machine'].geometry} material={nodes['Vending-machine'].material} userData={{ name: 'Vending-machine' }} />
        <mesh name="WallFan" geometry={nodes.WallFan.geometry} material={nodes.WallFan.material} userData={{ name: 'WallFan' }}>
          <mesh name="LightFan" geometry={nodes.LightFan.geometry} material={nodes.LightFan.material} userData={{ name: 'LightFan' }} />
        </mesh>
        <mesh name="WarningLight" geometry={nodes.WarningLight.geometry} material={nodes.WarningLight.material} userData={{ name: 'WarningLight' }}>
          <mesh name="Light" geometry={nodes.Light.geometry} material={nodes.Light.material} userData={{ name: 'Light' }} />
        </mesh>
        <mesh name="WarningLight2" geometry={nodes.WarningLight2.geometry} material={nodes.WarningLight2.material} userData={{ name: 'WarningLight2' }}>
          <mesh name="Light001" geometry={nodes.Light001.geometry} material={nodes.Light001.material} userData={{ name: 'Light.001' }} />
        </mesh>
        <mesh name="Pump" geometry={nodes.Pump.geometry} material={nodes.Pump.material} userData={{ name: 'Pump' }} />
        <mesh name="StoreWindow" geometry={nodes.StoreWindow.geometry} material={nodes.StoreWindow.material} userData={{ name: 'StoreWindow' }} />
        <mesh name="PlaneLight" geometry={nodes.PlaneLight.geometry} material={nodes.PlaneLight.material} userData={{ name: 'PlaneLight' }} />
        <mesh name="PlatformsLight" geometry={nodes.PlatformsLight.geometry} material={nodes.PlatformsLight.material} userData={{ name: 'Platforms.Light' }} />
        <mesh name="Text_Cyberstudio" geometry={nodes.Text_Cyberstudio.geometry} material={nodes.Text_Cyberstudio.material} userData={{ name: 'Text_Cyberstudio' }} />
        <mesh name="BanerLight" geometry={nodes.BanerLight.geometry} material={nodes.BanerLight.material} userData={{ name: 'BanerLight' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/station.glb')
